AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template
Globals:
  Function:
    Runtime: java8
    Timeout: 60
    Environment:
      Variables:
        REGION: ap-northeast-1
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-sample/f0f2440a3f60fbf5821d388bc767d247
      Handler: sample.App::handleRequest
      FunctionName: Scala3-HelloWorld
